version: '3'

services:
  SnapDump:
    build: .
    image: zweidenker/snap-dump:latest
    container_name: "SnapDump"
    ports:
      - "5556:5555"
    volumes:
      - "SnapDump:/snapshots"

volumes:
  SnapDump:
    external: true

