version: '3'

services:
  snapdump:
    build: .
    image: zweidenket/snap-dump:latest
    ports:
      - "5556:5555"
    volumes:
      - "SnapDump:/snapshots"

volumes:
  SnapDump:
    external: true

